import Link from 'next/link';
export function AboutContent(){return <div className="about-content">
 <section className="about-hero"><span className="eyebrow">SCIENTIFIC KNOW-HOW, SHARED.</span><h1>Turn experience<br/>into <em>discovery.</em></h1><p>BioSkillsHub is a home for the practical knowledge behind good research: reusable workflows that scientists can share, review and bring to their AI assistants.</p><div className="actions"><Link className="primary" href="/browse">Explore the skills catalogue →</Link><a className="outline" href="/#sign-in">Sign in to create or acquire</a></div></section>
 <section className="about-intro"><span className="eyebrow">WHAT IS A SKILL?</span><h2>More than a prompt.<br/>A method you can inspect.</h2><p>A skill is a readable Markdown file describing when a method applies, its inputs and outputs, a procedure, expert decisions, limitations and examples. It can also include supporting script text. It carries the context an assistant needs to help you follow a workflow.</p></section>
 <section className="about-steps" aria-label="How BioSkillsHub works">{[
 ['01','Find a method','Browse domains, read summaries and check the creator’s validation status before choosing a skill.'],
 ['02','Make it yours','Sign in and add a skill to your library. Download a specific version and its provenance, then review the instructions. All purchases in this demo are simulated: £0 is charged.'],
 ['03','Bring it to your assistant','Attach the Markdown to your assistant or retrieve it with the agent helper. Run tools in your own environment, with your approval. BioSkillsHub distributes instructions; it does not run experiments.']
 ].map(([n,title,body])=><article key={n}><span className="eyebrow">{n}</span><h3>{title}</h3><p>{body}</p></article>)}</section>
 <section className="about-intro"><span className="eyebrow">BUILT FOR CONTRIBUTORS</span><h2>Your workflow could help<br/>the next researcher.</h2><p>Write a skill, use a guided template, talk it through with AI, or import files and folders for AI-assisted conversion. Review and edit the result before publishing. AI tools require configured access; personal API usage may incur charges.</p><p>Published versions stay unchanged, so researchers can record exactly which instructions they used.</p></section>
 <section className="about-note"><h2>A research prototype, with clear boundaries.</h2><p>Built for the London AI × Bio Hack, September 2026. Creator-reported validation is not independent scientific verification. Prototype workflows need expert review. Skills are readable by their users, and imported instructions and scripts should be treated as untrusted until reviewed.</p><p>Codex is our integration target; Rosalind execution remains unverified. Community ratings are available for acquired skills; synthetic demo ratings and eval badges are labelled. Subscriptions and collaborative authorship remain roadmap previews.</p></section>
 </div>;}
export function PublicHeader(){return <header className="public-header"><Link href="/">BioSkillsHub</Link><nav aria-label="Public navigation"><Link href="/about">About</Link><Link href="/browse">Catalogue</Link><Link href="/#sign-in">Sign in</Link></nav></header>;}
