import {zipSync,strToU8} from 'fflate';
import {chromium,webkit} from 'playwright';
import {mobileCreatorRegression} from './rehearse-mobile-creator.mjs';
import pg from 'pg';
import net from 'node:net';
import {randomBytes,scryptSync,createHash} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {spawn,execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
const origin=process.env.APP_ORIGIN||'http://localhost:3004';
function privateUrl(value){try{return new URL(value);}catch{throw Error('Invalid private database/origin configuration.');}}
const appUrl=privateUrl(origin);
assert.ok(['localhost','127.0.0.1'].includes(appUrl.hostname),'Use a local rehearsal origin');
const schema=`rehearsal_${Date.now()}`;
const evidence=`.local/rehearsal/${schema}`;
await mkdir(evidence,{recursive:true,mode:0o700});
const url=privateUrl(process.env.DATABASE_URL);
assert.ok(['localhost','127.0.0.1'].includes(url.hostname));assert.equal(url.port,process.env.REHEARSAL_DB_PORT||'5442');
const admin=new pg.Client({connectionString:url.toString()});
// Refuse to test an existing service on the allocated app port.
await new Promise((resolve,reject)=>{const probe=net.createServer();probe.once('error',reject);probe.listen(Number(appUrl.port||3004),'127.0.0.1',()=>probe.close(resolve));});
await admin.connect();
let db,server,browser;
const steps=[];
const pass=s=>{steps.push(s);console.log(`PASS: ${s}`);};
try {
 await admin.query(`CREATE SCHEMA ${schema}`);
 url.searchParams.set('options',`-c search_path=${schema}`);
 db=new pg.Client({connectionString:url.toString()});await db.connect();
 await db.query(await readFile('db/schema.sql','utf8'));
 const passwords={};
 for(const id of ['wojtek','efe']) {
  const password=randomBytes(24).toString('hex'),salt=randomBytes(24).toString('hex');passwords[id]=password;
  await db.query('INSERT INTO users VALUES($1,$2,$3,$4)',[id,`${id} (rehearsal)`,'Synthetic software fixture',`${salt}:${scryptSync(password,salt,64).toString('hex')}`]);
 }
 server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',appUrl.port||'3004'],{env:{...process.env,DATABASE_URL:url.toString(),APP_ORIGIN:origin,OPENAI_API_KEY:'',OPENAI_MODEL:'',GITHUB_CLIENT_ID:'',GITHUB_CLIENT_SECRET:''},stdio:'ignore'});
 for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error('Rehearsal server could not start');try{if((await fetch(origin+'/api/auth/me')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await (process.env.REHEARSAL_BROWSER==='webkit'?webkit:chromium).launch({headless:true,executablePath:process.env.REHEARSAL_BROWSER_EXECUTABLE||undefined});
 if(process.env.REHEARSAL_MOBILE_ONLY!=='true'){
 let page=await browser.newPage({viewport:{width:1440,height:1000},recordVideo:{dir:evidence,size:{width:1440,height:1000}}});
 const errors=[];page.on('pageerror',e=>errors.push(e.name));
 async function login(id){const response=await page.request.post(origin+'/api/auth/login',{headers:{Origin:origin},data:{id,password:passwords[id]}});assert.equal(response.ok(),true,'Synthetic account session');await page.goto(origin+'/workspace');await page.getByRole('button',{name:'Creator studio',exact:true}).waitFor();}
 await page.goto(origin);await page.getByRole('heading',{name:/Turn experience/}).waitFor();
 assert.equal(await page.getByLabel('Password',{exact:true}).count(),0,'No password login form');
 await page.getByText('GitHub sign-in is temporarily unavailable.',{exact:false}).waitFor();
 await page.screenshot({path:evidence+'/landing-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Landing fits mobile');
 await page.screenshot({path:evidence+'/landing-mobile.png',fullPage:true});
 await page.goto(origin+'/about');await page.getByRole('heading',{name:/A method you can inspect/}).waitFor();
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(origin+'/browse');await page.getByRole('heading',{name:/Expertise/}).waitFor();
 await page.getByRole('link',{name:'Physics (0)',exact:true}).click();await page.getByRole('heading',{name:'No skills here yet.'}).waitFor();
 await login('wojtek');await page.getByRole('link',{name:'BioSkillsHub home',exact:true}).click();await page.getByRole('heading',{name:/Turn experience/}).waitFor();await page.getByRole('link',{name:'Open workspace',exact:true}).click();await page.getByRole('button',{name:'Creator studio',exact:true}).waitFor();pass('public landing, empty domain and synthetic account session');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'No narrow-screen overflow');
 assert.equal(await page.getByRole('button',{name:'Sign out',exact:true}).isVisible(),true,'Mobile sign-out reachable');
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'Creator studio',exact:true}).click();
 const title='Synthetic rehearsal protocol';
 pass('creator studio opened');

 await page.getByLabel('Domain',{exact:true}).selectOption({label:'Physics'});
 pass('new domain selected');
 await page.getByLabel('Skill title',{exact:true}).fill(title);
 await page.getByLabel('Short description').fill('A harmless synthetic fixture for the marketplace rehearsal; no scientific results.');
 for(const label of ['Use cases','Inputs','Outputs','Procedure','Expert decisions','Limitations','Examples']) await page.getByLabel(label,{exact:true}).fill(`Synthetic rehearsal ${label.toLowerCase()}; no scientific validation claimed.`);
 pass('guided answers completed');
 await page.getByRole('button',{name:'Use structured template',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('textarea.code')?.value.includes('## Procedure'));
 assert.equal(await page.getByRole('button',{name:'Guided authoring',exact:true}).getAttribute('class'),'chosen');
 assert.equal(await page.getByLabel('Import a Markdown file',{exact:false}).count(),0);
 const content=await page.getByLabel('Skill instructions').inputValue();
 await page.getByLabel('Validation evidence / status').fill('Synthetic software fixture; scientifically unvalidated');
 await page.getByLabel('Release notes').fill('Rehearsal version 1');
 assert.equal(await page.getByRole('button',{name:'Publish reviewed version'}).isDisabled(),true);
 await page.getByRole('button',{name:'Save draft',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();
 pass('guided template and draft save; publish disabled before review');
 assert.equal((await db.query('SELECT count(*) FROM versions')).rows[0].count,'0');
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Publish reviewed version'}).click();
 await page.getByRole('status').filter({hasText:'Published immutable version 1'}).waitFor();
 const skill=(await db.query('SELECT skill_id FROM versions')).rows[0].skill_id;
 pass('review and immutable version 1 publication');
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL(origin+'/#sign-in');await login('efe');
 await page.getByRole('button',{name:new RegExp(title)}).click();
 await page.getByRole('dialog').waitFor();
 assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Close details');
 await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>Boolean(document.activeElement?.closest('dialog'))),true,'Focus stays inside dialog');
 await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 assert.ok((await page.evaluate(()=>document.activeElement?.textContent))?.includes(title),'Focus returns to skill card');
 await page.getByRole('button',{name:new RegExp(title)}).click();
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Dialog fits narrow screen');
 await page.getByRole('button',{name:/Add to library/}).click();
 await page.getByRole('button',{name:'Confirm demo acquisition'}).click();
 await page.getByRole('button',{name:'Read selected version'}).click();
 await page.locator('.skill-content').waitFor();assert.equal(await page.locator('.skill-content').textContent(),content);
 const downloadReady=page.waitForEvent('download');await page.getByRole('button',{name:'Download selected skill',exact:true}).click();const download=await downloadReady;assert.equal(await readFile(await download.path(),'utf8'),content);
 await page.getByRole('heading',{name:'How to use this skill'}).waitFor();
 assert.ok((await page.getByLabel('Suggested task prompt').inputValue()).includes(skill));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Usage guide fits mobile');
 await page.screenshot({path:evidence+'/acquired-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Close details'}).click();
 await page.getByRole('button',{name:/^My library/}).click();await page.getByRole('button',{name:new RegExp(title)}).waitFor();
 pass('buyer browse, simulated acquisition, library, pinned content, keyboard focus and mobile layout');
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(origin+'/browse');await page.getByRole('heading',{name:title,exact:true}).waitFor();
 assert.equal(await page.locator('body').textContent().then(t=>t.includes('## Procedure')),false,'Public page omits instructions');
 assert.equal(await page.locator('[data-artwork-id]').count(),1,'Published skill has artwork');
 await page.getByRole('link',{name:'Physics (1)',exact:true}).click();
 await page.getByRole('heading',{name:title,exact:true}).waitFor();
 await page.screenshot({path:evidence+'/public-catalog.png',fullPage:true});
 await page.context().close(); // Stop fallback recording before any token is created.
 page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.name));page.setDefaultTimeout(15000);await login('efe');
 await page.getByRole('button',{name:'AI settings',exact:true}).click();
 const dummyKey='sk-browser-fixture-not-a-real-key';
 await page.getByLabel('OpenAI API key',{exact:true}).fill(dummyKey);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Enable personal key',exact:true}).click();
 assert.equal(await page.getByLabel('OpenAI API key',{exact:true}).inputValue(),'');
 assert.equal(await page.evaluate(key=>JSON.stringify({...localStorage,...sessionStorage}).includes(key),dummyKey),false);
 let personalSent=false;
 await page.route('**/api/recommend',async route=>{const body=route.request().postDataJSON();assert.equal(body.ai.apiKey,dummyKey);personalSent=true;await route.fulfill({json:{recommendations:[],note:'Fixture response'}});});
 await page.getByRole('button',{name:'Explore',exact:true}).click();await page.getByLabel('Research question').fill('Synthetic workflow');await page.getByRole('button',{name:'Find skills',exact:true}).click();await page.getByText('Fixture response',{exact:true}).waitFor();assert.equal(personalSent,true);
 pass('personal key recommendation request');await page.unroute('**/api/recommend');
 await page.getByRole('button',{name:'Creator studio',exact:true}).click();await page.getByRole('button',{name:'Chat with AI',exact:true}).click();
 pass('chat editor opened');let chatCount=0;
 await page.route('**/api/skill-chat',async route=>{const body=route.request().postDataJSON();assert.equal(body.ai.apiKey,dummyKey);chatCount++;if(chatCount===2){await route.fulfill({status:502,json:{error:'Fixture provider failure'}});return;}assert.equal(body.messages[0].content,'I count fluorescent objects.');if(body.action==='draft'){assert.ok(body.messages.some(m=>m.content==='I use TIFF images.'));await route.fulfill({json:{message:'Review the missing parameters.',draft:{title:'Conversational fixture workflow',summary:'Synthetic conversation-generated workflow for browser testing only.',domain:'Imaging',content}}});}else await route.fulfill({json:{message:'Which image format do you use?',draft:null}});});
 await page.getByLabel('Your workflow or answer').fill('I count fluorescent objects.');await page.getByRole('button',{name:'Send to skill assistant',exact:true}).click();await page.getByText('Which image format do you use?',{exact:true}).waitFor();pass('chat follow-up received');
 await page.getByLabel('Your workflow or answer').fill('I use TIFF images.');await page.getByRole('button',{name:'Send to skill assistant',exact:true}).click();await page.getByText('Fixture provider failure',{exact:true}).waitFor();pass('chat failure preserved');assert.equal(await page.getByLabel('Your workflow or answer').inputValue(),'I use TIFF images.');
 await page.getByRole('button',{name:'Create skill draft',exact:true}).click();await page.getByRole('button',{name:'Use draft in editor',exact:true}).waitFor();pass('chat preview received');const draftDownloadReady=page.waitForEvent('download');await page.getByRole('button',{name:'Download draft SKILL.md',exact:true}).click();const draftDownload=await draftDownloadReady;assert.equal(await readFile(await draftDownload.path(),'utf8'),content);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Chat preview fits mobile');
 await page.screenshot({path:evidence+'/chat-builder-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Use draft in editor',exact:true}).click();pass('chat draft applied');assert.equal(await page.getByRole('button',{name:'Chat with AI',exact:true}).getAttribute('class'),'chosen');assert.equal(await page.getByLabel('Your workflow or answer').count(),1);assert.equal(await page.getByLabel('Skill title',{exact:true}).inputValue(),'Conversational fixture workflow');pass('chat editor title verified');assert.equal(await page.getByLabel('Skill instructions').inputValue(),content);pass('chat editor content verified');assert.equal(await page.getByRole('button',{name:'Publish reviewed version'}).isDisabled(),true);
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();assert.equal((await db.query('SELECT count(*) FROM versions')).rows[0].count,'1');
 pass('chat draft saved');await page.unroute('**/api/skill-chat');await page.setViewportSize({width:1440,height:1000});pass('chat questions, failure retry, transcript context, draft review/save and mobile layout');
 page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Start a blank skill',exact:true}).click();await page.getByRole('button',{name:'Guided authoring',exact:true}).click();
 await page.getByLabel('Skill title',{exact:true}).fill('Guided AI fixture');await page.getByLabel('Short description').fill('Synthetic guided AI creation fixture requiring human review.');
 for(const label of ['Use cases','Inputs','Outputs','Procedure','Expert decisions','Limitations','Examples'])await page.getByLabel(label,{exact:true}).fill('Synthetic '+label+' fixture only.');
 let guidedCalls=0;await page.route('**/api/generate',async route=>{guidedCalls++;assert.equal(route.request().postDataJSON().ai.apiKey,dummyKey);await route.fulfill({json:{content,mode:'ai'}});});
 await page.getByRole('button',{name:'Generate AI draft',exact:true}).click();await page.getByRole('status').filter({hasText:'AI draft generated'}).waitFor();assert.equal(await page.getByRole('button',{name:'Guided authoring',exact:true}).getAttribute('class'),'chosen');assert.equal(await page.getByLabel('Skill instructions').inputValue(),content);assert.equal(guidedCalls,1);assert.equal(await page.getByRole('button',{name:'Publish reviewed version',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();await page.unroute('**/api/generate');pass('guided AI creation transfers to editable review-gated draft');
 page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Start a blank skill',exact:true}).click();await page.getByRole('button',{name:'Import files with AI',exact:true}).click();
 await mkdir(evidence+'/upload-fixture/scripts',{recursive:true});
 const scriptText='print("Synthetic fixture; do not execute during import")';
 await writeFile(evidence+'/upload-fixture/SKILL.md','Describe this synthetic workflow.');await writeFile(evidence+'/upload-fixture/scripts/check.py',scriptText);await writeFile(evidence+'/upload-fixture/.env','FIXTURE_ONLY=excluded');
 let importRequests=0;
 await page.route('**/api/skill-import',async route=>{const body=route.request().postDataJSON();importRequests++;assert.equal(body.confirmed,true);assert.equal(body.ai.apiKey,dummyKey);if(importRequests===1){assert.equal(body.files.length,1);assert.equal(body.files[0].path,'Workflow.java');}else{assert.equal(body.files.length,2);assert.ok(body.files.some(f=>f.path==='upload-fixture/scripts/check.py'&&f.content===scriptText));}assert.ok(!JSON.stringify(body.files).includes('FIXTURE_ONLY'));await route.fulfill({json:{message:'Review the original script before use.',draft:{title:'Imported synthetic workflow',summary:'A synthetic imported workflow for testing the review process.',domain:'Chemistry',content:content+'\n\n## Original supporting files\n\n'+scriptText}}});});
 await page.getByRole('note',{name:'How your API key is handled'}).waitFor();
 await page.getByLabel('Choose a single file or ZIP folder',{exact:true}).setInputFiles({name:'Workflow.java',mimeType:'text/markdown',buffer:Buffer.from('Standalone skill fixture')});await page.getByRole('status').filter({hasText:'1 files selected locally'}).waitFor();assert.equal(await page.getByRole('button',{name:'Analyse files with AI',exact:true}).isDisabled(),true);await page.getByLabel('I reviewed these files',{exact:false}).check();await page.getByRole('button',{name:'Analyse files with AI',exact:true}).click();await page.getByRole('button',{name:'Use imported draft in editor',exact:true}).waitFor();assert.equal(importRequests,1);
 await page.getByLabel('Choose a single file or ZIP folder',{exact:true}).setInputFiles({name:'workflow.zip',mimeType:'application/zip',buffer:Buffer.from(zipSync({'upload-fixture/SKILL.md':strToU8('Describe this synthetic workflow.'),'upload-fixture/scripts/check.py':strToU8(scriptText),'upload-fixture/.env':strToU8('FIXTURE_ONLY=excluded')}))});await page.getByRole('status').filter({hasText:'2 files selected locally'}).waitFor();assert.equal(importRequests,1);
 assert.equal(await page.getByRole('button',{name:'Analyse files with AI',exact:true}).isDisabled(),true);await page.getByLabel('I reviewed these files', {exact:false}).check();await page.getByRole('button',{name:'Analyse files with AI',exact:true}).click();await page.getByRole('button',{name:'Use imported draft in editor',exact:true}).waitFor();assert.equal(importRequests,2);await page.getByRole('status').filter({hasText:'AI analysis returned'}).waitFor();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Importer fits mobile');await page.screenshot({path:evidence+'/file-import-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Use imported draft in editor',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Import files with AI',exact:true}).getAttribute('class'),'chosen');assert.ok((await page.getByLabel('Skill instructions').inputValue()).includes(scriptText));assert.equal(await page.getByRole('button',{name:'Publish reviewed version'}).isDisabled(),true);
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();assert.equal((await db.query('SELECT count(*) FROM versions')).rows[0].count,'1');
 await page.unroute('**/api/skill-import');await page.setViewportSize({width:1440,height:1000});pass('Java file and ZIP selection, excluded private file, explicit AI consent, source retention and review-gated import');await page.reload();await page.getByRole('button',{name:'AI settings',exact:true}).click();await page.getByText('No hosted AI is configured.',{exact:false}).waitFor();
 pass('personal key explicit request, no browser persistence, refresh clears key');
 await page.getByRole('button',{name:'Connect agent',exact:true}).click();
 await page.getByLabel('Workspace name').fill('Disposable rehearsal');
 await page.getByRole('button',{name:'Create token',exact:true}).click();
 await page.locator('.token-secret code').waitFor();
 const token=await page.locator('.token-secret code').textContent();
 await page.getByRole('button',{name:/saved it.*hide token/}).click();
 const env={...process.env,BIOSKILLS_URL:origin,BIOSKILLS_TOKEN:token};
 const list=JSON.parse(execFileSync('python3',['scripts/agent_client.py','list'],{env,stdio:['ignore','pipe','pipe']}));
 assert.equal(list.skills.length,1);assert.equal(list.skills[0].id,skill);
 execFileSync('python3',['scripts/agent_client.py','get',skill,'1','--output',evidence+'/SKILL.md'],{env,stdio:'pipe'});
 const manifest=JSON.parse(await readFile(evidence+'/SKILL.md.manifest.json','utf8'));
 assert.equal(manifest.number,1);assert.equal(manifest.sha256,createHash('sha256').update(content).digest('hex'));
 pass('UI token transported privately to Python helper; pinned content and SHA-256 verified');
 await page.getByRole('button',{name:'Revoke',exact:true}).click();await page.getByRole('button',{name:'Revoked',exact:true}).waitFor();
 let revoked=false;try{execFileSync('python3',['scripts/agent_client.py','list'],{env,stdio:'pipe'});}catch{revoked=true;}assert.equal(revoked,true);
 assert.deepEqual(errors,[]);pass('revocation rejects helper access; no browser page errors');
 // Direct Markdown and editing must work with no hosted or personal AI key.
 let unexpectedAI=0;await page.route('**/api/generate',async route=>{unexpectedAI++;await route.abort();});
 await page.getByRole('button',{name:'Creator studio',exact:true}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Start a blank skill',exact:true}).click();await page.getByRole('button',{name:'Upload / edit Markdown',exact:true}).click();
 pass('manual Markdown editor opened');
 const manualContent=content+'\n\n<!-- '+('large Markdown fixture '.repeat(5000))+' -->';
 await page.getByLabel('Import a Markdown file',{exact:false}).setInputFiles({name:'workflow.MD',mimeType:'text/markdown',buffer:Buffer.from(manualContent)});
 await page.getByRole('status').filter({hasText:'Markdown loaded locally'}).waitFor();pass('manual Markdown file loaded');assert.equal(await page.getByLabel('Skill instructions').inputValue(),manualContent);
 assert.equal(await page.getByRole('note',{name:'How your API key is handled'}).count(),0,'API key notice does not appear as a Markdown error');
 await page.getByLabel('Skill title',{exact:true}).fill('Manual Markdown fixture');await page.getByLabel('Short description').fill('A fixture proving that Markdown creation does not require an AI key.');
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();
 pass('manual Markdown draft saved');
 const editedContent=manualContent+'\nManual edit verified.';await page.getByLabel('Skill instructions').fill(editedContent);await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();
 pass('manual edit saved');assert.equal(await page.getByRole('button',{name:'Publish reviewed version',exact:true}).isDisabled(),true);await page.getByLabel('I have reviewed the full instructions',{exact:false}).check();await page.getByRole('button',{name:'Publish reviewed version',exact:true}).click();await page.getByRole('status').filter({hasText:'Published immutable version 1'}).waitFor();
 assert.equal((await db.query('SELECT content FROM versions WHERE title=$1',['Manual Markdown fixture'])).rows[0].content,editedContent);assert.equal(unexpectedAI,0);await page.unroute('**/api/generate');
 assert.deepEqual(errors,[]);pass('large uppercase Markdown upload, manual editing, save/review/publish with no AI key or provider calls');
 // Invalid uploads and draft validation must preserve the last valid instructions.
 await page.getByLabel('Import a Markdown file',{exact:false}).setInputFiles({name:'invalid.md',mimeType:'text/markdown',buffer:Buffer.from([0xff,0xfe])});
 await page.getByRole('alert').filter({hasText:'must use UTF-8'}).waitFor();assert.equal(await page.getByLabel('Skill instructions').inputValue(),editedContent);
 await page.getByLabel('Import a Markdown file',{exact:false}).setInputFiles({name:'oversized.md',mimeType:'text/markdown',buffer:Buffer.alloc(300001,65)});
 await page.getByRole('alert').filter({hasText:'300 KB'}).waitFor();assert.equal(await page.getByLabel('Skill instructions').inputValue(),editedContent);
 await page.getByLabel('Skill instructions').fill('   ');await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('alert').filter({hasText:'Complete your draft: Skill instructions'}).waitFor();
 assert.equal((await db.query('SELECT content FROM versions WHERE title=$1',['Manual Markdown fixture'])).rows[0].content,editedContent);
 await page.getByLabel('Skill instructions').fill(editedContent);await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();
 pass('failed encoding/oversize uploads preserve editor; invalid draft cannot change a release; retry succeeds');
 await page.getByRole('button',{name:'Explore',exact:true}).click();await page.getByRole('button',{name:/Manual Markdown fixture/}).click();
 await page.getByRole('button',{name:'Restore selected version as a new release',exact:true}).click();await page.getByRole('status').filter({hasText:'Restored as new version 2. Existing releases remain unchanged.'}).waitFor();
 await page.getByRole('button',{name:/Add to library/}).click();await page.getByRole('button',{name:'Confirm demo acquisition',exact:true}).click();
 await page.getByRole('button',{name:'Read selected version',exact:true}).click();await page.locator('.skill-content').waitFor();assert.equal(await page.locator('.skill-content').textContent(),editedContent);
 await page.getByRole('dialog').getByRole('combobox').selectOption('1');await page.getByRole('button',{name:'Read selected version',exact:true}).click();await page.locator('.skill-content').waitFor();assert.equal(await page.locator('.skill-content').textContent(),editedContent);
 await page.getByRole('button',{name:'Close details',exact:true}).click();pass('creator restore and explicit earlier-version retrieval preserve content');
 // Custom-heading Markdown publishes unchanged; optional adaptation needs explicit consent and review.
 const nativeContent=process.env.NATIVE_SKILL_FIXTURE?await readFile(process.env.NATIVE_SKILL_FIXTURE,'utf8'):'---\nname: native-workflow\ndescription: Inspect example inputs with explicit settings and reproducible outputs.\n---\n\n# Native workflow\n\n## First interaction\nAsk which inputs to inspect. Preserve raw inputs and record decisions and limitations before reporting results.\n';
 await page.getByRole('button',{name:'Creator studio',exact:true}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Start a blank skill',exact:true}).click();await page.getByRole('button',{name:'Upload / edit Markdown',exact:true}).click();
 await page.getByLabel('Import a Markdown file',{exact:false}).setInputFiles({name:'SKILL.md',mimeType:'text/markdown',buffer:Buffer.from(nativeContent)});
 await page.getByLabel('Adapt to BioSkillsHub’s suggested structure with AI',{exact:true}).waitFor();assert.equal(await page.getByLabel('Adapt to BioSkillsHub’s suggested structure with AI',{exact:true}).isChecked(),false);
 assert.ok((await page.getByLabel('Skill title',{exact:true}).inputValue()).length>0);assert.ok((await page.getByLabel('Short description').inputValue()).length>0);
 assert.equal(await page.getByLabel('Skill instructions').inputValue(),nativeContent);
 assert.equal(await page.getByRole('button',{name:'Analyse files with AI',exact:true}).count(),0);
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Publish reviewed version',exact:true}).isDisabled(),true);
 await page.getByLabel('I have reviewed the full instructions',{exact:false}).check();await page.getByRole('button',{name:'Publish reviewed version',exact:true}).click();await page.getByRole('status').filter({hasText:'Published immutable version 1'}).waitFor();
 const nativeTitle=await page.getByLabel('Skill title',{exact:true}).inputValue();assert.equal((await db.query('SELECT content FROM versions WHERE title=$1',[nativeTitle])).rows[0].content,nativeContent);
 await page.getByLabel('Adapt to BioSkillsHub’s suggested structure with AI',{exact:true}).check();assert.equal(await page.getByRole('button',{name:'Analyse files with AI',exact:true}).isDisabled(),true);
 await page.getByLabel('Adapt to BioSkillsHub’s suggested structure with AI',{exact:true}).uncheck();assert.equal(await page.getByRole('button',{name:'Analyse files with AI',exact:true}).count(),0);
 pass('custom-heading Markdown publishes unchanged without AI; optional adaptation defaults off');
 await page.getByRole('button',{name:'AI settings',exact:true}).click();await page.getByLabel('OpenAI API key',{exact:true}).fill(dummyKey);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Enable personal key',exact:true}).click();
 await page.getByRole('button',{name:'Creator studio',exact:true}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Start a blank skill',exact:true}).click();await page.getByLabel('Import a Markdown file',{exact:false}).setInputFiles({name:'SKILL.md',mimeType:'text/markdown',buffer:Buffer.from(nativeContent)});
 await page.getByLabel('Adapt to BioSkillsHub’s suggested structure with AI',{exact:true}).check();
 let conversionCalls=0;
 await page.route('**/api/skill-import',async route=>{conversionCalls++;const body=route.request().postDataJSON();assert.equal(body.confirmed,true);assert.equal(body.files[0].content,nativeContent);if(conversionCalls===1){await route.fulfill({status:502,json:{error:'Conversion fixture failure'}});return;}await route.fulfill({json:{message:'Synthetic conversion; review before publishing.',draft:{title:'Converted workflow fixture',summary:'Synthetic conversion result for testing the schema and review workflow.',domain:'Imaging',content}}});});
 assert.equal(await page.getByRole('button',{name:'Analyse files with AI',exact:true}).isDisabled(),true);assert.equal(conversionCalls,0);
 await page.getByLabel('I reviewed these files',{exact:false}).check();await page.getByRole('button',{name:'Analyse files with AI',exact:true}).click();await page.getByRole('alert').filter({hasText:'Conversion fixture failure'}).waitFor();assert.equal(await page.getByLabel('Skill instructions').inputValue(),nativeContent);
 await page.getByRole('button',{name:'Analyse files with AI',exact:true}).click();await page.getByRole('button',{name:'Use imported draft in editor',exact:true}).waitFor();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Use imported draft in editor',exact:true}).click();
 assert.equal(conversionCalls,2);assert.equal(await page.getByRole('button',{name:'Upload / edit Markdown',exact:true}).getAttribute('class'),'chosen');assert.equal(await page.getByLabel('Skill instructions').inputValue(),content);
 assert.equal(await page.getByRole('button',{name:'Publish reviewed version',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();
 await page.getByLabel('I have reviewed the full instructions',{exact:false}).check();await page.getByRole('button',{name:'Publish reviewed version',exact:true}).click();await page.getByRole('status').filter({hasText:'Published immutable version 1'}).waitFor();
 assert.equal((await db.query('SELECT content FROM versions WHERE title=$1',['Converted workflow fixture'])).rows[0].content,content);await page.unroute('**/api/skill-import');
 pass('optional Markdown adaptation requires consent and review; failure preserves source; all methods keep their selected interface');
 await page.getByRole('button',{name:'Import files with AI',exact:true}).click();
 const nativeArchive=process.env.NATIVE_ZIP_FIXTURE?await readFile(process.env.NATIVE_ZIP_FIXTURE):Buffer.from(zipSync({'native/SKILL.md':strToU8(nativeContent),'native/.git/history':strToU8('x'.repeat(250000))},{level:0}));
 await page.getByLabel('Choose a single file or ZIP folder',{exact:true}).setInputFiles({name:'native.zip',mimeType:'application/zip',buffer:nativeArchive});
 await page.getByRole('status').filter({hasText:'files selected locally'}).waitFor();
 assert.ok(await page.locator('.import-file-list summary').count()>0);
 assert.equal(await page.getByRole('button',{name:'Analyse files with AI',exact:true}).isDisabled(),true);
 assert.equal(await page.locator('.import-file-list').getByText(/\.git\//).count(),0);
 pass('ZIP with excluded repository metadata previews locally without credentials or provider calls');

 await db.query("UPDATE sessions SET expires_at=now()-interval '1 second' WHERE user_id='efe'");await page.reload();await page.waitForURL(origin+'/#sign-in');await page.getByRole('heading',{name:/Turn experience/}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Creator studio',exact:true}).count(),0);assert.deepEqual(errors,[]);pass('expired session returns to public landing without cached workspace');
 }
 await mobileCreatorRegression({browser,origin,password:passwords.wojtek,db,evidence});pass('mobile dialog, price, Other domain, actionable save errors, recovery and publication');
 await writeFile(evidence+'/result.json',JSON.stringify({time:new Date().toISOString(),scope:'Disposable schema in Wojtek database; synthetic software only',steps},null,2),{mode:0o600});
} catch(e) {console.error('Rehearsal failed:',e.name,'after',steps.at(-1)||'startup','(details suppressed to protect credentials)');process.exitCode=1;}
finally {
 await browser?.close();
 if(server&&server.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));}
 await db?.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();
 console.log('Temporary server stopped and rehearsal schema removed.');
 console.log(`Private rehearsal evidence: ${evidence}`);
}
